{% set name = "hooking" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hooking-{{ version }}.tar.gz
  sha256: f986fde23991b08658a30e1f1e23e69cab058b3a48109879419ba116ec6dff76

build:
  entry_points:
    - hooking = hooking.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - hooking
  commands:
    - pip check
    - hooking --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/hooking
  summary: Generic dual-paradigm hooking mechanism
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
